### ISSUE TITLE
Accessories don't follow draw order and can't be used in social slots

### ISSUE THREAD

**Issue by IdrisQe** [634R-64M35/VisAcc#1]
I'm sure you're aware of this, but just wanting to say if there's a way to fix this it'd be much appreciated-
in Vanilla, if you have two accessories occupying the "feet" area of the player, only the one placed lowest on your accessory list will show, but that doesn't seem to work with this mod, for example things like the Aglet getting overridden by the Shoe Spikes regardless of where it is in the accessory slots unless the Shoe Spikes are set to hidden.

Also any accessory modified to be visible won't go into vanity slots- I know there are other mods that do this, but I feel like it's important functionality for a mod specifically making things give vanity cosmetics.

**Comment by 634R-64M35** [comment]
I'm not sure if there's a fix for the first issue due to how equip slots are handled but I'll look into it
As for the second problem, the accessory thing is not a mod problem, relogic removed the ability to move some accessories into vanity slots, and while I was going to fix it, the next terraria update will revert the change anwyays.

**Comment by IdrisQe** [comment]
Oh right, I forgot the next update is going to change that.

But still, if the first one could be fixed that would be nice too! I assume it's a related issue to dyes not working on them?

**Comment by 634R-64M35** [comment]
Yea the dyes thing is unrelated I think, but next update will add dye support as well as visiblity support and fix this issue as well
